export interface Category {
  id: string;
  name: string;
  emoji: string;
  color: string;
}

export const categories: Category[] = [
  { id: 'fiction', name: 'Fiction', emoji: '📖', color: 'bg-amber-50 text-amber-700 border-amber-200' },
  { id: 'non-fiction', name: 'Non-Fiction', emoji: '📚', color: 'bg-blue-50 text-blue-700 border-blue-200' },
  { id: 'romance', name: 'Romance', emoji: '💕', color: 'bg-pink-50 text-pink-700 border-pink-200' },
  { id: 'thriller', name: 'Thriller', emoji: '🔍', color: 'bg-red-50 text-red-700 border-red-200' },
  { id: 'mystery', name: 'Mystery', emoji: '🕵️', color: 'bg-purple-50 text-purple-700 border-purple-200' },
  { id: 'science-fiction', name: 'Science Fiction', emoji: '🚀', color: 'bg-cyan-50 text-cyan-700 border-cyan-200' },
  { id: 'fantasy', name: 'Fantasy', emoji: '🧙', color: 'bg-violet-50 text-violet-700 border-violet-200' },
  { id: 'philosophy', name: 'Philosophy', emoji: '🤔', color: 'bg-stone-50 text-stone-700 border-stone-200' },
  { id: 'religion', name: 'Religion', emoji: '🙏', color: 'bg-yellow-50 text-yellow-700 border-yellow-200' },
  { id: 'history', name: 'History', emoji: '🏛️', color: 'bg-orange-50 text-orange-700 border-orange-200' },
  { id: 'science', name: 'Science', emoji: '🔬', color: 'bg-teal-50 text-teal-700 border-teal-200' },
  { id: 'psychology', name: 'Psychology', emoji: '🧠', color: 'bg-fuchsia-50 text-fuchsia-700 border-fuchsia-200' },
  { id: 'self-help', name: 'Self-Help', emoji: '🌱', color: 'bg-green-50 text-green-700 border-green-200' },
  { id: 'spirituality', name: 'Spirituality', emoji: '✨', color: 'bg-indigo-50 text-indigo-700 border-indigo-200' },
  { id: 'biography', name: 'Biography', emoji: '👤', color: 'bg-sky-50 text-sky-700 border-sky-200' },
  { id: 'autobiography', name: 'Autobiography', emoji: '📝', color: 'bg-lime-50 text-lime-700 border-lime-200' },
  { id: 'poetry', name: 'Poetry', emoji: '🌸', color: 'bg-rose-50 text-rose-700 border-rose-200' },
  { id: 'drama', name: 'Drama', emoji: '🎭', color: 'bg-slate-50 text-slate-700 border-slate-200' },
  { id: 'horror', name: 'Horror', emoji: '👻', color: 'bg-gray-50 text-gray-700 border-gray-200' },
  { id: 'adventure', name: 'Adventure', emoji: '⛰️', color: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  { id: 'comedy', name: 'Comedy', emoji: '😂', color: 'bg-yellow-50 text-yellow-700 border-yellow-200' },
  { id: 'crime', name: 'Crime', emoji: '💎', color: 'bg-zinc-50 text-zinc-700 border-zinc-200' },
  { id: 'classic', name: 'Classics', emoji: '🏛️', color: 'bg-neutral-50 text-neutral-700 border-neutral-200' },
  { id: 'business', name: 'Business', emoji: '💼', color: 'bg-blue-50 text-blue-700 border-blue-200' },
  { id: 'economics', name: 'Economics', emoji: '📊', color: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  { id: 'politics', name: 'Politics', emoji: '⚖️', color: 'bg-red-50 text-red-700 border-red-200' },
  { id: 'sociology', name: 'Sociology', emoji: '👥', color: 'bg-orange-50 text-orange-700 border-orange-200' },
  { id: 'technology', name: 'Technology', emoji: '💻', color: 'bg-cyan-50 text-cyan-700 border-cyan-200' },
  { id: 'mathematics', name: 'Mathematics', emoji: '📐', color: 'bg-indigo-50 text-indigo-700 border-indigo-200' },
  { id: 'medicine', name: 'Medicine', emoji: '🏥', color: 'bg-teal-50 text-teal-700 border-teal-200' },
  { id: 'art', name: 'Art', emoji: '🎨', color: 'bg-pink-50 text-pink-700 border-pink-200' },
  { id: 'music', name: 'Music', emoji: '🎵', color: 'bg-purple-50 text-purple-700 border-purple-200' },
  { id: 'travel', name: 'Travel', emoji: '✈️', color: 'bg-sky-50 text-sky-700 border-sky-200' },
  { id: 'cooking', name: 'Cooking', emoji: '🍳', color: 'bg-orange-50 text-orange-700 border-orange-200' },
  { id: 'health', name: 'Health', emoji: '💪', color: 'bg-green-50 text-green-700 border-green-200' },
  { id: 'parenting', name: 'Parenting', emoji: '👶', color: 'bg-rose-50 text-rose-700 border-rose-200' },
  { id: 'education', name: 'Education', emoji: '🎓', color: 'bg-blue-50 text-blue-700 border-blue-200' },
  { id: 'nature', name: 'Nature', emoji: '🌿', color: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  { id: 'environment', name: 'Environment', emoji: '🌍', color: 'bg-teal-50 text-teal-700 border-teal-200' },
  { id: 'astronomy', name: 'Astronomy', emoji: '🔭', color: 'bg-indigo-50 text-indigo-700 border-indigo-200' },
  { id: 'mythology', name: 'Mythology', emoji: '🐉', color: 'bg-violet-50 text-violet-700 border-violet-200' },
  { id: 'humor', name: 'Humor', emoji: '😄', color: 'bg-yellow-50 text-yellow-700 border-yellow-200' },
  { id: 'true-crime', name: 'True Crime', emoji: '🔎', color: 'bg-red-50 text-red-700 border-red-200' },
  { id: 'memoir', name: 'Memoir', emoji: '📔', color: 'bg-amber-50 text-amber-700 border-amber-200' },
  { id: 'graphic-novels', name: 'Graphic Novels', emoji: '🖼️', color: 'bg-fuchsia-50 text-fuchsia-700 border-fuchsia-200' },
  { id: 'young-adult', name: 'Young Adult', emoji: '🌟', color: 'bg-lime-50 text-lime-700 border-lime-200' },
  { id: 'children', name: "Children's", emoji: '🧸', color: 'bg-pink-50 text-pink-700 border-pink-200' },
  { id: 'war', name: 'War & Military', emoji: '⚔️', color: 'bg-stone-50 text-stone-700 border-stone-200' },
];

export const categorySearchMap: Record<string, string[]> = {
  'fiction': ['best fiction books', 'bestselling novels', 'fiction'],
  'non-fiction': ['best nonfiction books', 'bestselling nonfiction', 'nonfiction books'],
  'romance': ['best romance novels', 'romance books', 'love stories'],
  'thriller': ['best thriller books', 'bestselling thriller', 'suspense novels'],
  'mystery': ['best mystery novels', 'mystery books', 'detective fiction'],
  'science-fiction': ['best science fiction books', 'sci-fi novels', 'scifi books'],
  'fantasy': ['best fantasy books', 'fantasy novels', 'magical fiction'],
  'philosophy': ['best philosophy books', 'philosophy', 'philosophical'],
  'religion': ['best religious books', 'religious books', 'spiritual books'],
  'history': ['best history books', 'historical books', 'bestselling history'],
  'science': ['best science books', 'popular science', 'scientific'],
  'psychology': ['best psychology books', 'psychology', 'mental health books'],
  'self-help': ['best self-help books', 'self improvement', 'personal development'],
  'spirituality': ['best spirituality books', 'spiritual books', 'mindfulness'],
  'biography': ['best biography books', 'biographies', 'famous lives'],
  'autobiography': ['best autobiography', 'autobiographies', 'memoir'],
  'poetry': ['best poetry books', 'poetry', 'poems'],
  'drama': ['best drama books', 'dramatic plays', 'theater'],
  'horror': ['best horror books', 'horror novels', 'scary books'],
  'adventure': ['best adventure books', 'adventure novels', 'adventure stories'],
  'comedy': ['best comedy books', 'funny books', 'humor books'],
  'crime': ['best crime novels', 'crime fiction', 'criminal fiction'],
  'classic': ['classic literature', 'bestselling classics', 'classic novels'],
  'business': ['best business books', 'business books', 'leadership'],
  'economics': ['best economics books', 'economics', 'finance books'],
  'politics': ['best politics books', 'political books', 'government'],
  'sociology': ['best sociology books', 'sociology', 'society'],
  'technology': ['best technology books', 'tech books', 'programming'],
  'mathematics': ['best mathematics books', 'math books', 'calculus'],
  'medicine': ['best medicine books', 'medical books', 'health'],
  'art': ['best art books', 'art books', 'painting'],
  'music': ['best music books', 'music books', 'composers'],
  'travel': ['best travel books', 'travel books', 'travel guides'],
  'cooking': ['best cooking books', 'cookbooks', 'recipes'],
  'health': ['best health books', 'health books', 'fitness'],
  'parenting': ['best parenting books', 'parenting', 'family'],
  'education': ['best education books', 'education', 'learning'],
  'nature': ['best nature books', 'nature books', 'wildlife'],
  'environment': ['best environment books', 'environment', 'ecology'],
  'astronomy': ['best astronomy books', 'astronomy', 'space'],
  'mythology': ['best mythology books', 'mythology', 'myths'],
  'humor': ['best humor books', 'funny books', 'comedy'],
  'true-crime': ['best true crime books', 'true crime', 'crime investigation'],
  'memoir': ['best memoir books', 'memoir', 'personal stories'],
  'graphic-novels': ['best graphic novels', 'graphic novels', 'comics'],
  'young-adult': ['best young adult books', 'YA novels', 'teen fiction'],
  'children': ['best children books', 'kids books', 'children\'s fiction'],
  'war': ['best war books', 'military history', 'war stories'],
};
