export interface Category {
  id: string;
  name: string;
  emoji: string;
  color: string;
}

export const categories: Category[] = [
  { id: 'fiction', name: 'Fiction', emoji: '📖', color: 'bg-amber-50 text-amber-700 border-amber-200' },
  { id: 'non-fiction', name: 'Non-Fiction', emoji: '📚', color: 'bg-blue-50 text-blue-700 border-blue-200' },
  { id: 'romance', name: 'Romance', emoji: '💕', color: 'bg-pink-50 text-pink-700 border-pink-200' },
  { id: 'thriller', name: 'Thriller', emoji: '🔍', color: 'bg-red-50 text-red-700 border-red-200' },
  { id: 'mystery', name: 'Mystery', emoji: '🕵️', color: 'bg-purple-50 text-purple-700 border-purple-200' },
  { id: 'science-fiction', name: 'Science Fiction', emoji: '🚀', color: 'bg-cyan-50 text-cyan-700 border-cyan-200' },
  { id: 'fantasy', name: 'Fantasy', emoji: '🧙', color: 'bg-violet-50 text-violet-700 border-violet-200' },
  { id: 'philosophy', name: 'Philosophy', emoji: '🤔', color: 'bg-stone-50 text-stone-700 border-stone-200' },
  { id: 'religion', name: 'Religion', emoji: '🙏', color: 'bg-yellow-50 text-yellow-700 border-yellow-200' },
  { id: 'history', name: 'History', emoji: '🏛️', color: 'bg-orange-50 text-orange-700 border-orange-200' },
  { id: 'science', name: 'Science', emoji: '🔬', color: 'bg-teal-50 text-teal-700 border-teal-200' },
  { id: 'psychology', name: 'Psychology', emoji: '🧠', color: 'bg-fuchsia-50 text-fuchsia-700 border-fuchsia-200' },
  { id: 'self-help', name: 'Self-Help', emoji: '🌱', color: 'bg-green-50 text-green-700 border-green-200' },
  { id: 'spirituality', name: 'Spirituality', emoji: '✨', color: 'bg-indigo-50 text-indigo-700 border-indigo-200' },
  { id: 'biography', name: 'Biography', emoji: '👤', color: 'bg-sky-50 text-sky-700 border-sky-200' },
  { id: 'autobiography', name: 'Autobiography', emoji: '📝', color: 'bg-lime-50 text-lime-700 border-lime-200' },
  { id: 'poetry', name: 'Poetry', emoji: '🌸', color: 'bg-rose-50 text-rose-700 border-rose-200' },
  { id: 'drama', name: 'Drama', emoji: '🎭', color: 'bg-slate-50 text-slate-700 border-slate-200' },
  { id: 'horror', name: 'Horror', emoji: '👻', color: 'bg-gray-50 text-gray-700 border-gray-200' },
  { id: 'adventure', name: 'Adventure', emoji: '⛰️', color: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  { id: 'comedy', name: 'Comedy', emoji: '😂', color: 'bg-yellow-50 text-yellow-700 border-yellow-200' },
  { id: 'crime', name: 'Crime', emoji: '💎', color: 'bg-zinc-50 text-zinc-700 border-zinc-200' },
  { id: 'classic', name: 'Classics', emoji: '🏛️', color: 'bg-neutral-50 text-neutral-700 border-neutral-200' },
  { id: 'business', name: 'Business', emoji: '💼', color: 'bg-blue-50 text-blue-700 border-blue-200' },
  { id: 'economics', name: 'Economics', emoji: '📊', color: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  { id: 'politics', name: 'Politics', emoji: '⚖️', color: 'bg-red-50 text-red-700 border-red-200' },
  { id: 'sociology', name: 'Sociology', emoji: '👥', color: 'bg-orange-50 text-orange-700 border-orange-200' },
  { id: 'technology', name: 'Technology', emoji: '💻', color: 'bg-cyan-50 text-cyan-700 border-cyan-200' },
  { id: 'mathematics', name: 'Mathematics', emoji: '📐', color: 'bg-indigo-50 text-indigo-700 border-indigo-200' },
  { id: 'medicine', name: 'Medicine', emoji: '🏥', color: 'bg-teal-50 text-teal-700 border-teal-200' },
  { id: 'art', name: 'Art', emoji: '🎨', color: 'bg-pink-50 text-pink-700 border-pink-200' },
  { id: 'music', name: 'Music', emoji: '🎵', color: 'bg-purple-50 text-purple-700 border-purple-200' },
  { id: 'travel', name: 'Travel', emoji: '✈️', color: 'bg-sky-50 text-sky-700 border-sky-200' },
  { id: 'cooking', name: 'Cooking', emoji: '🍳', color: 'bg-orange-50 text-orange-700 border-orange-200' },
  { id: 'health', name: 'Health', emoji: '💪', color: 'bg-green-50 text-green-700 border-green-200' },
  { id: 'parenting', name: 'Parenting', emoji: '👶', color: 'bg-rose-50 text-rose-700 border-rose-200' },
  { id: 'education', name: 'Education', emoji: '🎓', color: 'bg-blue-50 text-blue-700 border-blue-200' },
  { id: 'nature', name: 'Nature', emoji: '🌿', color: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  { id: 'environment', name: 'Environment', emoji: '🌍', color: 'bg-teal-50 text-teal-700 border-teal-200' },
  { id: 'astronomy', name: 'Astronomy', emoji: '🔭', color: 'bg-indigo-50 text-indigo-700 border-indigo-200' },
  { id: 'mythology', name: 'Mythology', emoji: '🐉', color: 'bg-violet-50 text-violet-700 border-violet-200' },
  { id: 'humor', name: 'Humor', emoji: '😄', color: 'bg-yellow-50 text-yellow-700 border-yellow-200' },
  { id: 'true-crime', name: 'True Crime', emoji: '🔎', color: 'bg-red-50 text-red-700 border-red-200' },
  { id: 'memoir', name: 'Memoir', emoji: '📔', color: 'bg-amber-50 text-amber-700 border-amber-200' },
  { id: 'graphic-novels', name: 'Graphic Novels', emoji: '🖼️', color: 'bg-fuchsia-50 text-fuchsia-700 border-fuchsia-200' },
  { id: 'young-adult', name: 'Young Adult', emoji: '🌟', color: 'bg-lime-50 text-lime-700 border-lime-200' },
  { id: 'children', name: "Children's", emoji: '🧸', color: 'bg-pink-50 text-pink-700 border-pink-200' },
  { id: 'war', name: 'War & Military', emoji: '⚔️', color: 'bg-stone-50 text-stone-700 border-stone-200' },
];

export const categorySearchMap: Record<string, string[]> = {
  'fiction': ['fiction', 'novel', 'literature'],
  'non-fiction': ['nonfiction', 'non-fiction', 'essay'],
  'romance': ['romance', 'love story'],
  'thriller': ['thriller', 'suspense'],
  'mystery': ['mystery', 'detective', 'whodunit'],
  'science-fiction': ['science fiction', 'sci-fi', 'scifi'],
  'fantasy': ['fantasy', 'magical', 'wizard'],
  'philosophy': ['philosophy', 'ethics', 'logic'],
  'religion': ['religion', 'theology', 'faith'],
  'history': ['history', 'historical'],
  'science': ['science', 'scientific', 'research'],
  'psychology': ['psychology', 'mental', 'behavior'],
  'self-help': ['self-help', 'self improvement', 'personal development'],
  'spirituality': ['spirituality', 'meditation', 'mindfulness'],
  'biography': ['biography', 'life story'],
  'autobiography': ['autobiography', 'memoir', 'journal'],
  'poetry': ['poetry', 'poems', 'verse'],
  'drama': ['drama', 'play', 'theater'],
  'horror': ['horror', 'terror', 'gothic'],
  'adventure': ['adventure', 'expedition', 'journey'],
  'comedy': ['comedy', 'humor', 'satire'],
  'crime': ['crime', 'criminal', 'noir'],
  'classic': ['classic', 'classics', 'literary fiction'],
  'business': ['business', 'management', 'leadership'],
  'economics': ['economics', 'finance', 'economy'],
  'politics': ['politics', 'political', 'government'],
  'sociology': ['sociology', 'society', 'social'],
  'technology': ['technology', 'computers', 'programming'],
  'mathematics': ['mathematics', 'math', 'calculus'],
  'medicine': ['medicine', 'medical', 'health'],
  'art': ['art', 'painting', 'design'],
  'music': ['music', 'musical', 'composer'],
  'travel': ['travel', 'voyage', 'explore'],
  'cooking': ['cooking', 'recipe', 'culinary'],
  'health': ['health', 'wellness', 'fitness'],
  'parenting': ['parenting', 'family', 'childcare'],
  'education': ['education', 'learning', 'teaching'],
  'nature': ['nature', 'wildlife', 'outdoors'],
  'environment': ['environment', 'ecology', 'climate'],
  'astronomy': ['astronomy', 'space', 'cosmos'],
  'mythology': ['mythology', 'myths', 'legends'],
  'humor': ['humor', 'funny', 'comical'],
  'true-crime': ['true crime', 'criminal investigation'],
  'memoir': ['memoir', 'remembrance', 'recollection'],
  'graphic-novels': ['graphic novel', 'comics', 'manga'],
  'young-adult': ['young adult', 'ya', 'teen'],
  'children': ['children', 'kids', 'juvenile'],
  'war': ['war', 'military', 'combat'],
};
